INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (1, 4, 'AF', 'AFG', 'Afghanistan', 'Afghanistan');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (2, 8, 'AL', 'ALB', 'Albania', 'Albanie');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (3, 10, 'AQ', 'ATA', 'Antarctica', 'Antarctique');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (4, 12, 'DZ', 'DZA', 'Algeria', 'Algérie');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (5, 16, 'AS', 'ASM', 'American Samoa', 'Samoa Américaines');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (6, 20, 'AD', 'AND', 'Andorra', 'Andorre');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (7, 24, 'AO', 'AGO', 'Angola', 'Angola');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (8, 28, 'AG', 'ATG', 'Antigua and Barbuda', 'Antigua-et-Barbuda');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (9, 31, 'AZ', 'AZE', 'Azerbaijan', 'Azerbaïdjan');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (10, 32, 'AR', 'ARG', 'Argentina', 'Argentine');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (11, 36, 'AU', 'AUS', 'Australia', 'Australie');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (12, 40, 'AT', 'AUT', 'Austria', 'Autriche');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (13, 44, 'BS', 'BHS', 'Bahamas', 'Bahamas');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (14, 48, 'BH', 'BHR', 'Bahrain', 'Bahreïn');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (15, 50, 'BD', 'BGD', 'Bangladesh', 'Bangladesh');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (16, 51, 'AM', 'ARM', 'Armenia', 'Arménie');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (17, 52, 'BB', 'BRB', 'Barbados', 'Barbade');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (18, 56, 'BE', 'BEL', 'Belgium', 'Belgique');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (19, 60, 'BM', 'BMU', 'Bermuda', 'Bermudes');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (20, 64, 'BT', 'BTN', 'Bhutan', 'Bhoutan');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (21, 68, 'BO', 'BOL', 'Bolivia', 'Bolivie');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (22, 70, 'BA', 'BIH', 'Bosnia and Herzegovina', 'Bosnie-Herzégovine');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (23, 72, 'BW', 'BWA', 'Botswana', 'Botswana');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (24, 74, 'BV', 'BVT', 'Bouvet Island', 'Île Bouvet');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (25, 76, 'BR', 'BRA', 'Brazil', 'Brésil');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (26, 84, 'BZ', 'BLZ', 'Belize', 'Belize');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (27, 86, 'IO', 'IOT', 'British Indian Ocean Territory', 'Territoire Britannique de l''Océan Indien');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (28, 90, 'SB', 'SLB', 'Solomon Islands', 'Îles Salomon');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (29, 92, 'VG', 'VGB', 'British Virgin Islands', 'Îles Vierges Britanniques');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (30, 96, 'BN', 'BRN', 'Brunei Darussalam', 'Brunéi Darussalam');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (31, 100, 'BG', 'BGR', 'Bulgaria', 'Bulgarie');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (32, 104, 'MM', 'MMR', 'Myanmar', 'Myanmar');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (33, 108, 'BI', 'BDI', 'Burundi', 'Burundi');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (34, 112, 'BY', 'BLR', 'Belarus', 'Bélarus');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (35, 116, 'KH', 'KHM', 'Cambodia', 'Cambodge');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (36, 120, 'CM', 'CMR', 'Cameroon', 'Cameroun');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (37, 124, 'CA', 'CAN', 'Canada', 'Canada');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (38, 132, 'CV', 'CPV', 'Cape Verde', 'Cap-vert');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (39, 136, 'KY', 'CYM', 'Cayman Islands', 'Îles Caïmanes');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (40, 140, 'CF', 'CAF', 'Central African', 'République Centrafricaine');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (41, 144, 'LK', 'LKA', 'Sri Lanka', 'Sri Lanka');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (42, 148, 'TD', 'TCD', 'Chad', 'Tchad');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (43, 152, 'CL', 'CHL', 'Chile', 'Chili');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (44, 156, 'CN', 'CHN', 'China', 'Chine');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (45, 158, 'TW', 'TWN', 'Taiwan', 'Taïwan');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (46, 162, 'CX', 'CXR', 'Christmas Island', 'Île Christmas');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (47, 166, 'CC', 'CCK', 'Cocos (Keeling) Islands', 'Îles Cocos (Keeling)');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (48, 170, 'CO', 'COL', 'Colombia', 'Colombie');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (49, 174, 'KM', 'COM', 'Comoros', 'Comores');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (50, 175, 'YT', 'MYT', 'Mayotte', 'Mayotte');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (51, 178, 'CG', 'COG', 'Republic of the Congo', 'République du Congo');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (52, 180, 'CD', 'COD', 'The Democratic Republic Of The Congo', 'République Démocratique du Congo');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (53, 184, 'CK', 'COK', 'Cook Islands', 'Îles Cook');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (54, 188, 'CR', 'CRI', 'Costa Rica', 'Costa Rica');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (55, 191, 'HR', 'HRV', 'Croatia', 'Croatie');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (56, 192, 'CU', 'CUB', 'Cuba', 'Cuba');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (57, 196, 'CY', 'CYP', 'Cyprus', 'Chypre');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (58, 203, 'CZ', 'CZE', 'Czech Republic', 'République Tchèque');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (59, 204, 'BJ', 'BEN', 'Benin', 'Bénin');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (60, 208, 'DK', 'DNK', 'Denmark', 'Danemark');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (61, 212, 'DM', 'DMA', 'Dominica', 'Dominique');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (62, 214, 'DO', 'DOM', 'Dominican Republic', 'République Dominicaine');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (63, 218, 'EC', 'ECU', 'Ecuador', 'Équateur');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (64, 222, 'SV', 'SLV', 'El Salvador', 'El Salvador');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (65, 226, 'GQ', 'GNQ', 'Equatorial Guinea', 'Guinée Équatoriale');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (66, 231, 'ET', 'ETH', 'Ethiopia', 'Éthiopie');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (67, 232, 'ER', 'ERI', 'Eritrea', 'Érythrée');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (68, 233, 'EE', 'EST', 'Estonia', 'Estonie');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (69, 234, 'FO', 'FRO', 'Faroe Islands', 'Îles Féroé');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (70, 238, 'FK', 'FLK', 'Falkland Islands', 'Îles (malvinas) Falkland');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (71, 239, 'GS', 'SGS', 'South Georgia and the South Sandwich Islands', 'Géorgie du Sud et les Îles Sandwich du Sud');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (72, 242, 'FJ', 'FJI', 'Fiji', 'Fidji');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (73, 246, 'FI', 'FIN', 'Finland', 'Finlande');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (74, 248, 'AX', 'ALA', 'Åland Islands', 'Îles Åland');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (75, 250, 'FR', 'FRA', 'France', 'France');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (76, 254, 'GF', 'GUF', 'French Guiana', 'Guyane Française');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (77, 258, 'PF', 'PYF', 'French Polynesia', 'Polynésie Française');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (78, 260, 'TF', 'ATF', 'French Southern Territories', 'Terres Australes Françaises');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (79, 262, 'DJ', 'DJI', 'Djibouti', 'Djibouti');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (80, 266, 'GA', 'GAB', 'Gabon', 'Gabon');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (81, 268, 'GE', 'GEO', 'Georgia', 'Géorgie');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (82, 270, 'GM', 'GMB', 'Gambia', 'Gambie');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (83, 275, 'PS', 'PSE', 'Occupied Palestinian Territory', 'Territoire Palestinien Occupé');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (84, 276, 'DE', 'DEU', 'Germany', 'Allemagne');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (85, 288, 'GH', 'GHA', 'Ghana', 'Ghana');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (86, 292, 'GI', 'GIB', 'Gibraltar', 'Gibraltar');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (87, 296, 'KI', 'KIR', 'Kiribati', 'Kiribati');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (88, 300, 'GR', 'GRC', 'Greece', 'Grèce');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (89, 304, 'GL', 'GRL', 'Greenland', 'Groenland');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (90, 308, 'GD', 'GRD', 'Grenada', 'Grenade');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (91, 312, 'GP', 'GLP', 'Guadeloupe', 'Guadeloupe');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (92, 316, 'GU', 'GUM', 'Guam', 'Guam');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (93, 320, 'GT', 'GTM', 'Guatemala', 'Guatemala');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (94, 324, 'GN', 'GIN', 'Guinea', 'Guinée');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (95, 328, 'GY', 'GUY', 'Guyana', 'Guyana');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (96, 332, 'HT', 'HTI', 'Haiti', 'Haïti');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (97, 334, 'HM', 'HMD', 'Heard Island and McDonald Islands', 'Îles Heard et Mcdonald');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (98, 336, 'VA', 'VAT', 'Vatican City State', 'Saint-Siège (état de la Cité du Vatican)');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (99, 340, 'HN', 'HND', 'Honduras', 'Honduras');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (100, 344, 'HK', 'HKG', 'Hong Kong', 'Hong-Kong');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (101, 348, 'HU', 'HUN', 'Hungary', 'Hongrie');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (102, 352, 'IS', 'ISL', 'Iceland', 'Islande');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (103, 356, 'IN', 'IND', 'India', 'Inde');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (104, 360, 'ID', 'IDN', 'Indonesia', 'Indonésie');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (105, 364, 'IR', 'IRN', 'Islamic Republic of Iran', 'République Islamique d''Iran');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (106, 368, 'IQ', 'IRQ', 'Iraq', 'Iraq');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (107, 372, 'IE', 'IRL', 'Ireland', 'Irlande');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (108, 376, 'IL', 'ISR', 'Israel', 'Israël');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (109, 380, 'IT', 'ITA', 'Italy', 'Italie');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (110, 384, 'CI', 'CIV', 'Côte d''Ivoire', 'Côte d''Ivoire');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (111, 388, 'JM', 'JAM', 'Jamaica', 'Jamaïque');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (112, 392, 'JP', 'JPN', 'Japan', 'Japon');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (113, 398, 'KZ', 'KAZ', 'Kazakhstan', 'Kazakhstan');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (114, 400, 'JO', 'JOR', 'Jordan', 'Jordanie');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (115, 404, 'KE', 'KEN', 'Kenya', 'Kenya');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (116, 408, 'KP', 'PRK', 'Democratic People''s Republic of Korea', 'République Populaire Démocratique de Corée');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (117, 410, 'KR', 'KOR', 'Republic of Korea', 'République de Corée');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (118, 414, 'KW', 'KWT', 'Kuwait', 'Koweït');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (119, 417, 'KG', 'KGZ', 'Kyrgyzstan', 'Kirghizistan');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (120, 418, 'LA', 'LAO', 'Lao People''s Democratic Republic', 'République Démocratique Populaire Lao');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (121, 422, 'LB', 'LBN', 'Lebanon', 'Liban');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (122, 426, 'LS', 'LSO', 'Lesotho', 'Lesotho');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (123, 428, 'LV', 'LVA', 'Latvia', 'Lettonie');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (124, 430, 'LR', 'LBR', 'Liberia', 'Libéria');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (125, 434, 'LY', 'LBY', 'Libyan Arab Jamahiriya', 'Jamahiriya Arabe Libyenne');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (126, 438, 'LI', 'LIE', 'Liechtenstein', 'Liechtenstein');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (127, 440, 'LT', 'LTU', 'Lithuania', 'Lituanie');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (128, 442, 'LU', 'LUX', 'Luxembourg', 'Luxembourg');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (129, 446, 'MO', 'MAC', 'Macao', 'Macao');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (130, 450, 'MG', 'MDG', 'Madagascar', 'Madagascar');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (131, 454, 'MW', 'MWI', 'Malawi', 'Malawi');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (132, 458, 'MY', 'MYS', 'Malaysia', 'Malaisie');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (133, 462, 'MV', 'MDV', 'Maldives', 'Maldives');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (134, 466, 'ML', 'MLI', 'Mali', 'Mali');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (135, 470, 'MT', 'MLT', 'Malta', 'Malte');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (136, 474, 'MQ', 'MTQ', 'Martinique', 'Martinique');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (137, 478, 'MR', 'MRT', 'Mauritania', 'Mauritanie');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (138, 480, 'MU', 'MUS', 'Mauritius', 'Maurice');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (139, 484, 'MX', 'MEX', 'Mexico', 'Mexique');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (140, 492, 'MC', 'MCO', 'Monaco', 'Monaco');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (141, 496, 'MN', 'MNG', 'Mongolia', 'Mongolie');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (142, 498, 'MD', 'MDA', 'Republic of Moldova', 'République de Moldova');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (143, 500, 'MS', 'MSR', 'Montserrat', 'Montserrat');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (144, 504, 'MA', 'MAR', 'Morocco', 'Maroc');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (145, 508, 'MZ', 'MOZ', 'Mozambique', 'Mozambique');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (146, 512, 'OM', 'OMN', 'Oman', 'Oman');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (147, 516, 'NA', 'NAM', 'Namibia', 'Namibie');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (148, 520, 'NR', 'NRU', 'Nauru', 'Nauru');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (149, 524, 'NP', 'NPL', 'Nepal', 'Népal');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (150, 528, 'NL', 'NLD', 'Netherlands', 'Pays-Bas');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (151, 530, 'AN', 'ANT', 'Netherlands Antilles', 'Antilles Néerlandaises');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (152, 533, 'AW', 'ABW', 'Aruba', 'Aruba');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (153, 540, 'NC', 'NCL', 'New Caledonia', 'Nouvelle-Calédonie');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (154, 548, 'VU', 'VUT', 'Vanuatu', 'Vanuatu');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (155, 554, 'NZ', 'NZL', 'New Zealand', 'Nouvelle-Zélande');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (156, 558, 'NI', 'NIC', 'Nicaragua', 'Nicaragua');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (157, 562, 'NE', 'NER', 'Niger', 'Niger');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (158, 566, 'NG', 'NGA', 'Nigeria', 'Nigéria');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (159, 570, 'NU', 'NIU', 'Niue', 'Niué');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (160, 574, 'NF', 'NFK', 'Norfolk Island', 'Île Norfolk');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (161, 578, 'NO', 'NOR', 'Norway', 'Norvège');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (162, 580, 'MP', 'MNP', 'Northern Mariana Islands', 'Îles Mariannes du Nord');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (163, 581, 'UM', 'UMI', 'United States Minor Outlying Islands', 'Îles Mineures Éloignées des États-Unis');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (164, 583, 'FM', 'FSM', 'Federated States of Micronesia', 'États Fédérés de Micronésie');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (165, 584, 'MH', 'MHL', 'Marshall Islands', 'Îles Marshall');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (166, 585, 'PW', 'PLW', 'Palau', 'Palaos');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (167, 586, 'PK', 'PAK', 'Pakistan', 'Pakistan');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (168, 591, 'PA', 'PAN', 'Panama', 'Panama');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (169, 598, 'PG', 'PNG', 'Papua New Guinea', 'Papouasie-Nouvelle-Guinée');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (170, 600, 'PY', 'PRY', 'Paraguay', 'Paraguay');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (171, 604, 'PE', 'PER', 'Peru', 'Pérou');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (172, 608, 'PH', 'PHL', 'Philippines', 'Philippines');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (173, 612, 'PN', 'PCN', 'Pitcairn', 'Pitcairn');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (174, 616, 'PL', 'POL', 'Poland', 'Pologne');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (175, 620, 'PT', 'PRT', 'Portugal', 'Portugal');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (176, 624, 'GW', 'GNB', 'Guinea-Bissau', 'Guinée-Bissau');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (177, 626, 'TL', 'TLS', 'Timor-Leste', 'Timor-Leste');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (178, 630, 'PR', 'PRI', 'Puerto Rico', 'Porto Rico');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (179, 634, 'QA', 'QAT', 'Qatar', 'Qatar');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (180, 638, 'RE', 'REU', 'Réunion', 'Réunion');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (181, 642, 'RO', 'ROU', 'Romania', 'Roumanie');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (182, 643, 'RU', 'RUS', 'Russian Federation', 'Fédération de Russie');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (183, 646, 'RW', 'RWA', 'Rwanda', 'Rwanda');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (184, 654, 'SH', 'SHN', 'Saint Helena', 'Sainte-Hélène');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (185, 659, 'KN', 'KNA', 'Saint Kitts and Nevis', 'Saint-Kitts-et-Nevis');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (186, 660, 'AI', 'AIA', 'Anguilla', 'Anguilla');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (187, 662, 'LC', 'LCA', 'Saint Lucia', 'Sainte-Lucie');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (188, 666, 'PM', 'SPM', 'Saint-Pierre and Miquelon', 'Saint-Pierre-et-Miquelon');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (189, 670, 'VC', 'VCT', 'Saint Vincent and the Grenadines', 'Saint-Vincent-et-les Grenadines');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (190, 674, 'SM', 'SMR', 'San Marino', 'Saint-Marin');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (191, 678, 'ST', 'STP', 'Sao Tome and Principe', 'Sao Tomé-et-Principe');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (192, 682, 'SA', 'SAU', 'Saudi Arabia', 'Arabie Saoudite');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (193, 686, 'SN', 'SEN', 'Senegal', 'Sénégal');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (194, 690, 'SC', 'SYC', 'Seychelles', 'Seychelles');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (195, 694, 'SL', 'SLE', 'Sierra Leone', 'Sierra Leone');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (196, 702, 'SG', 'SGP', 'Singapore', 'Singapour');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (197, 703, 'SK', 'SVK', 'Slovakia', 'Slovaquie');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (198, 704, 'VN', 'VNM', 'Vietnam', 'Viet Nam');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (199, 705, 'SI', 'SVN', 'Slovenia', 'Slovénie');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (200, 706, 'SO', 'SOM', 'Somalia', 'Somalie');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (201, 710, 'ZA', 'ZAF', 'South Africa', 'Afrique du Sud');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (202, 716, 'ZW', 'ZWE', 'Zimbabwe', 'Zimbabwe');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (203, 724, 'ES', 'ESP', 'Spain', 'Espagne');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (204, 732, 'EH', 'ESH', 'Western Sahara', 'Sahara Occidental');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (205, 736, 'SD', 'SDN', 'Sudan', 'Soudan');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (206, 740, 'SR', 'SUR', 'Suriname', 'Suriname');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (207, 744, 'SJ', 'SJM', 'Svalbard and Jan Mayen', 'Svalbard etÎle Jan Mayen');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (208, 748, 'SZ', 'SWZ', 'Swaziland', 'Swaziland');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (209, 752, 'SE', 'SWE', 'Sweden', 'Suède');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (210, 756, 'CH', 'CHE', 'Switzerland', 'Suisse');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (211, 760, 'SY', 'SYR', 'Syrian Arab Republic', 'République Arabe Syrienne');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (212, 762, 'TJ', 'TJK', 'Tajikistan', 'Tadjikistan');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (213, 764, 'TH', 'THA', 'Thailand', 'Thaïlande');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (214, 768, 'TG', 'TGO', 'Togo', 'Togo');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (215, 772, 'TK', 'TKL', 'Tokelau', 'Tokelau');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (216, 776, 'TO', 'TON', 'Tonga', 'Tonga');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (217, 780, 'TT', 'TTO', 'Trinidad and Tobago', 'Trinité-et-Tobago');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (218, 784, 'AE', 'ARE', 'United Arab Emirates', 'Émirats Arabes Unis');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (219, 788, 'TN', 'TUN', 'Tunisia', 'Tunisie');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (220, 792, 'TR', 'TUR', 'Turkey', 'Turquie');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (221, 795, 'TM', 'TKM', 'Turkmenistan', 'Turkménistan');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (222, 796, 'TC', 'TCA', 'Turks and Caicos Islands', 'Îles Turks et Caïques');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (223, 798, 'TV', 'TUV', 'Tuvalu', 'Tuvalu');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (224, 800, 'UG', 'UGA', 'Uganda', 'Ouganda');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (225, 804, 'UA', 'UKR', 'Ukraine', 'Ukraine');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (226, 807, 'MK', 'MKD', 'The Former Yugoslav Republic of Macedonia', 'L''ex-République Yougoslave de Macédoine');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (227, 818, 'EG', 'EGY', 'Egypt', 'Égypte');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (228, 826, 'GB', 'GBR', 'United Kingdom', 'Royaume-Uni');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (229, 833, 'IM', 'IMN', 'Isle of Man', 'Île de Man');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (230, 834, 'TZ', 'TZA', 'United Republic Of Tanzania', 'République-Unie de Tanzanie');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (231, 840, 'US', 'USA', 'United States', 'États-Unis');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (232, 850, 'VI', 'VIR', 'U.S. Virgin Islands', 'Îles Vierges des États-Unis');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (233, 854, 'BF', 'BFA', 'Burkina Faso', 'Burkina Faso');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (234, 858, 'UY', 'URY', 'Uruguay', 'Uruguay');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (235, 860, 'UZ', 'UZB', 'Uzbekistan', 'Ouzbékistan');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (236, 862, 'VE', 'VEN', 'Venezuela', 'Venezuela');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (237, 876, 'WF', 'WLF', 'Wallis and Futuna', 'Wallis et Futuna');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (238, 882, 'WS', 'WSM', 'Samoa', 'Samoa');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (239, 887, 'YE', 'YEM', 'Yemen', 'Yémen');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (240, 891, 'CS', 'SCG', 'Serbia and Montenegro', 'Serbie-et-Monténégro');
INSERT INTO arthurius.country (id, code, alpha2, alpha3, name_en, name_fr) VALUES (241, 894, 'ZM', 'ZMB', 'Zambia', 'Zambie');